### PR TITLE
Fixes to app redirects, upstream errors & proper headers

### LINKED ISSUE #8: 301 redirects do not work
It looks like redirects do not work as they redirect you to `http://main:8001/login/?next=/dashboard/` for example

### PR DESCRIPTION
**Pull request by FabioFleitas**
This PR addresses a few things:
1. It resolves #8 which was causing any 301 redirects from the upstream apps to not work properly
2. Properly handles errors by moving to the next upstream app using `proxy_next_upstream`. This means that if a Heroku app has any issues with responding, it will move to the next app
3. Sets commonly used headers that are needed as part of load balancing

### CODE REVIEW

**Review by dmytrostriletskyi — APPROVED** [review]

**Comment by dmytrostriletskyi** [comment]
@FabioFleitas, hi!

Thanks for your contribution!

1. I've fixed continuous integration (Travis CI) build.
2. I've approved the pull request.

Please, update your branch (as there are fixes for CI in the `develop` branch).
After, you will be able to merge it! :)

**Comment by dmytrostriletskyi** [comment]
@FabioFleitas, have you faced any problems with merging your changes? :)

**Comment by FabioFleitas** [comment]
@dmytrostriletskyi Usually for our team if there are any branch changes we do a re-approval. Didn't realize it was good to merge now, so will go ahead and do so!

**Comment by FabioFleitas** [comment]
Actually - I'm unable to merge
Screen Shot 2020-07-20 at 9 41 10 AM

**Comment by dmytrostriletskyi** [comment]
Seems, only I can merge pull requests from forks. I thought an owner of a pull request can do it if all other checks are passed.

**Comment by dmytrostriletskyi** [comment]
Thank you again! :)

**Pull request merged**
